# Import library

In [1]:
import pandas as pd
import numpy as np

# Read dataset

Dataset obtained https://www.kaggle.com/datasets/utarasetyaw/data-set-destination-in-bali/

In [2]:
df_combination = pd.read_csv('./dataset/combination.csv')
df_combination.head()

Place 1                   Place 2   \
0       Pantai Pasih Uug  Pantai Angel's Billabong   
1         Pantai Diamond               Pantai Atuh   
2         Tanjung Benoa           Pantai Waterblow   
3  Tari Barong dan Keris                Sari Merta   
4  Tari Barong dan Keris                Sari Merta   

                        Place 3             Place 4           Place 5  
0              Pantai Kelingking  Pantai Crystal Bay              NaN  
1               Bukit Teletubies                 NaN              NaN  
2                   Pura Uluwatu      Pantai Pandawa  Pantai Jimbaran  
3               Pura Tirta Empul     Pantai Jimbaran              NaN  
4  Objek Wisata Desa Panglipuran     Pantai Jimbaran              NaN

## Dataset rating

In [3]:
df_rating = pd.read_csv('./dataset/rating.csv')
df_rating.head()

User_Id  Place_Id            Nama Tempat  Place_Rating
0        1         2   Agung Bali Oleh-Oleh             3
1        1         7       Aloha Ubud Swing             5
2        1         8         Bali Bird Park             5
3        1        12      Big Garden Corner             2
4        1        13  Wanagiri Hidden Hills             5

In [4]:
df_rating.dtypes

User_Id          int64
Place_Id         int64
Nama Tempat     object
Place_Rating     int64
dtype: object

Get user count

In [5]:
user_count = df_rating['User_Id'].nunique()
user_count

100

In [6]:
df_rating['User_Id'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int64)

## Dataset tourism

In [7]:
df_tourism = pd.read_csv('./dataset/tourism.csv')
df_tourism.head()

Place_Id                     Place_Name  \
0         1              Agrowisata Satria   
1         2                     Agung Bali   
2         3  Wisata Air Panas Toya Bungkah   
3         4         Air Terjun Aling-Aling   
4         5          Air Terjun Tegenungan   

                                         Description  Weekend Holiday Price  \
0  Agrowisata Satria menawarkan 'rasa' Bali pada ...                  50000   
1  Dapatkan berbagai produk oleh-oleh khas Bali b...                      0   
2  Pemandian air panas di dekat gunung Batur (Pem...                  70000   
3  Keberadaan air terjun ini semakin mempercantik...                  20000   
4  Bosan dengan wisata alam pantai dan ingin meni...                  20000   

   Weekday Price    Category      City  Rating  \
0          50000  Agrowisata   Gianyar     3.0   
1              0     Belanja    Badung     4.0   
2          70000        Alam    Bangli     4.0   
3          20000        Alam  Buleleng     4.5   
4          20000        Alam   Gianyar     4.0   

                                              Alamat  \
0   Manukaya, Kec. Tampaksiring, Kabupaten Gianya...   
1          Jln. Dewi Sri No.18XX, Kuta, Badung, Bali   
2  Batur Tengah, Kec. Kintamani, Kabupaten Bangli...   
3  Jl. Raya Desa Sambangan, Banjar, Sambangan, Ke...   
4  Jl. Ir. Sutami, Kemenuh, Kec. Sukawati, Kabupa...   

                               Coordinate       Lat        Long Gambar  
0  -8.402228546131536, 115.32296693687739 -8.402229  115.322967      V  
1    -8.700234336021559, 115.176534407375 -8.700234  115.176534      V  
2  -8.251298580809106, 115.39981444195475 -8.251299  115.399814      V  
3  -8.173073590748519, 115.10513024047802 -8.173074  115.105130      V  
4  -8.575191460385602, 115.28870189592831 -8.575191  115.288702      V

In [8]:
df_tourism.dtypes

Place_Id                   int64
Place_Name                object
Description               object
Weekend Holiday Price      int64
Weekday Price              int64
Category                  object
City                      object
Rating                   float64
Alamat                    object
Coordinate                object
Lat                      float64
Long                     float64
Gambar                    object
dtype: object

Get POI count

In [9]:
poi_count = df_rating['Place_Id'].nunique()
poi_count

75

In [10]:
np.sort(df_rating['Place_Id'].unique())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75], dtype=int64)

# Membuat matriks user-rating

In [11]:
matrix_user_rating = np.zeros((poi_count, user_count))

In [12]:
for i in range(0, poi_count):
    for j in range(0, user_count):
        try:
            matrix_user_rating[i][j] = df_rating[(df_rating['User_Id'] == i + 1 )& (df_rating['Place_Id'] == j + 1)].iloc[0]['Place_Rating']
        except Exception:
            continue

In [13]:
matrix_user_rating

array([[0., 3., 0., ..., 0., 0., 0.],
       [0., 3., 5., ..., 0., 0., 0.],
       [4., 5., 0., ..., 0., 0., 0.],
       ...,
       [0., 3., 0., ..., 0., 0., 0.],
       [4., 4., 5., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [14]:
df_user_rating = pd.DataFrame(matrix_user_rating,
                              index=range(1, poi_count + 1),
                              columns=range(1, user_count + 1))
df_user_rating.head()


1    2    3    4    5    6    7    8    9    10   ...  91   92   93   94   \
1  0.0  3.0  0.0  0.0  0.0  0.0  5.0  5.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  3.0  5.0  0.0  2.0  3.0  5.0  5.0  0.0  5.0  ...  0.0  0.0  0.0  0.0   
3  4.0  5.0  0.0  5.0  0.0  1.0  0.0  5.0  4.0  0.0  ...  0.0  0.0  0.0  0.0   
4  4.0  0.0  3.0  5.0  0.0  0.0  0.0  1.0  0.0  5.0  ...  0.0  0.0  0.0  0.0   
5  1.0  0.0  5.0  0.0  4.0  0.0  0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0  0.0   

   95   96   97   98   99   100  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  
5  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 100 columns]

In [15]:
df_user_rating.to_csv('./dataset/user_rating.csv', index=False)